language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake autopoint autotools-dev libtool libxml2-dev libcppunit-dev

before_script:
  - wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
  - unzip -q android-ndk-r21d-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r21
  - export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
  - export SILENT=true
  - git clone -b master --depth 1 https://github.com/aria2/aria2
  - git clone -b master --depth 1 https://github.com/c-ares/c-ares
  - git clone -b master --depth 1 https://github.com/libexpat/libexpat
  - git clone -b master --depth 1 https://github.com/madler/zlib
  - git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl
  - git clone -b master --depth 1 https://github.com/libssh2/libssh2

script:
  - ./build_all.sh
  - file ./bin/armeabi-v7a/bin/aria2c
  - file ./bin/arm64-v8a/bin/aria2c
  - file ./bin/x86/bin/aria2c
  - file ./bin/x86_64/bin/aria2c
