#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build Aria2-android

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - 'x64.sh'
  schedule:
    - cron: 10 1 3 * *
  watch:
    types: [started]

env:
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  GITHUB_REPO: jsda/aria2-android
  NDK_VER: android-ndk-r21d-linux-x86_64.zip
  TZ: Asia/Taipei

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential git curl ca-certificates \
        libxml2-dev libcppunit-dev autoconf automake autotools-dev autopoint libtool pkg-config zip

    - name: Organize files
      run: |
        echo "======================="
        git clone -b master --depth 1 https://github.com/aria2/aria2
        git clone -b master --depth 1 https://github.com/c-ares/c-ares
        git clone -b master --depth 1 https://github.com/libexpat/libexpat
        git clone -b master --depth 1 https://github.com/sqlite/sqlite
        git clone -b master --depth 1 https://github.com/madler/zlib
        git clone -b master --depth 1 https://github.com/libssh2/libssh2
        git clone -b OpenSSL_1_1_1-stable --depth 1 https://github.com/openssl/openssl
        wget -q https://dl.google.com/android/repository/$NDK_VER
        unzip -q $NDK_VER
        rm -rf $NDK_VER
        cd android-ndk-*
        export ANDROID_NDK_HOME=$PWD
        cd ..
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export SILENT=true
        mkdir -p output
        export OUTPUT_DIR=$PWD/output
        ./build_all.sh
        echo "Space usage:"
        echo "======================="
        echo "$(df -h)"
        echo "======================="
        echo "$PWD"
        echo "======================="
        echo "$(ls -fl $OUTPUT_DIR)"
        echo "======================="

    - name: SSH connection to Actions
      uses: jsda/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Upload Packages
      id: upload_packages
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd output
        git init
        git config user.name "actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "$(date "+%Y%m%d-%H%M")"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git" HEAD:Build
