#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build Aria2-android

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - 'x64.sh'
  schedule:
    - cron: 0 1 3 * *
  watch:
    types: [started]

env:
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: true
  GITHUB_REPO: jsda/aria2-android
  NDK_VER: android-ndk-r21d-linux-x86_64.zip
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential git curl ca-certificates \
        libxml2-dev libcppunit-dev autoconf automake autotools-dev autopoint libtool pkg-config zip

    - name: SSH connection to Actions
      uses: jsda/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Organize files
      run: |
        echo "======================="
        wget https://dl.google.com/android/repository/$NDK_VER
        unzip -q $NDK_VER
        rm -rf $NDK_VER
        cd android-ndk-*
        export ANDROID_NDK_HOME=$PWD
        cd ..
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export SILENT=true
        ./build_all.sh
        cd ..
        echo "Space usage:"
        echo "======================="
        echo "$(df -h)"
        echo "======================="
        zip -9 -r aria2-armeabi-v7a.zip ./bin/armeabi-v7a/bin/aria2c
        zip -9 -r aria2-arm64-v8a.zip ./bin/arm64-v8a/bin/aria2c
        zip -9 -r aria2-x86.zip ./bin/x86/bin/aria2c
        zip -9 -r aria2-x86_64.zip ./bin/x86_64/bin/aria2c
        mkdir -p aria2build
        mv aria2-*.zip aria2build
        echo "::set-env name=DATE::$(date "+%Y%m%d-%H%M")"

    - name: Upload Packages
      id: upload_packages
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd aria2build
        git init
        git config user.name "actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "$DATE"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git" HEAD:Build
